### ISSUE TITLE
[ember deploy production] Error: EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by openhouse** [iheanyi/ember-cli-deploy-digitalocean#13]
When running `ember deploy production` I get this error:

```
Error: EISDIR: illegal operation on a directory, read
Error: EISDIR: illegal operation on a directory, read
    at Object.fs.readSync (fs.js:656:19)
    at FSMonitor._measure (/Users/username/Sites/project/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.readSync (/Users/username/Sites/project/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at tryReadSync (fs.js:457:20)
    at Object.fs.readFileSync (fs.js:494:19)
    at FSMonitor._measure (/Users/username/Sites/project/node_modules/heimdalljs-fs-monitor/index.js:66:21)
    at Object.readFileSync (/Users/username/Sites/project/node_modules/heimdalljs-fs-monitor/index.js:82:30)
    at Class.configure (/Users/username/Sites/project/node_modules/ember-cli-deploy-digitalocean/lib/digitalocean-deploy-plugin.js:52:33)
    at Class.superWrapper [as configure] (/Users/username/Sites/project/node_modules/ember-cli-deploy-digitalocean/node_modules/ember-cli-deploy-plugin/node_modules/core-object/lib/assign-properties.js:32:18)
Pipeline aborted
```

`ember do:provision` seemed to work correctly and I selected production.

Thanks! 🎛 📡✨

**Comment by openhouse** [comment]
Ok, the problem was `PRIVATE_KEY_DIR` needs to be the path to the private key file.  I originally had it as the path to the directory containing the private key.
